### Get all
GET http://localhost:3000/employees

### Get specific
GET http://localhost:3000/employees/61f1bdb9aa60bc380be73cdc

### Post one
POST http://localhost:3000/employees
Content-Type: application/json

{
    "name": "this one is totally new",
    "salary": 1111,
    "age": 44
  }